apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncWave }}"
type: Opaque
stringData:
  dbUser: {{ .Values.secrets.dbUser | quote }}
  dbPassword: {{ .Values.secrets.dbPassword | quote }}
